export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_EMAIL: '/verify-email',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  ACTIVITY: '/activity',
  LEARN: '/learn',
  CODE: '/code',
  DOCS: '/docs',
  DOCS_SUMMARY: '/docs/summary/:docId',
  NOTES: '/notes',
  NOTE_EDITOR: '/notes/:id',
  NOTE_NEW: '/notes/new',
  PROGRESS: '/progress',
  QUIZ: '/quiz/:topicId',
  QUIZ_RESULTS: '/quiz/:topicId/results',
  SETTINGS: '/settings',
  QUIZ_HISTORY: '/quiz-history',
} as const;
